import Challenge.EvmProof.Program
import Challenge.Sha256.Reference.Bytecode
set_option warningAsError true
set_option maxRecDepth 10000
set_option maxHeartbeats 1000000
/-!
# Structural certificate for the frozen SHA-256 artifact

This is the instruction-boundary view of the literal reference bytecode.
It is data, not a compiler provenance assumption: the theorem below ties its
assembly to `referenceBytecode` byte-for-byte. Generic decoder and jump-target
theorems can therefore operate structurally rather than repeatedly reducing the
whole 1,524-byte array.
-/

namespace Challenge.Sha256.Reference.Proofs.Bytecode.Artifact

open EvmSemantics
open EvmSemantics.EVM
open YulEvmCompiler

def referenceInstructions : List Instr :=
[YulEvmCompiler.Instr.push 2 27,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 4 4294967295,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 3 }),
 YulEvmCompiler.Instr.push 1 32,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.SUB)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 2 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 4 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.OR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.AND)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 2 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 68,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 0 }),
 YulEvmCompiler.Instr.push 1 3,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHR)),
 YulEvmCompiler.Instr.push 2 48,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 18,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 4 }),
 YulEvmCompiler.Instr.push 2 4,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 60,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 7,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 5 }),
 YulEvmCompiler.Instr.push 2 4,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.XOR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.XOR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 109,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 0 }),
 YulEvmCompiler.Instr.push 1 10,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHR)),
 YulEvmCompiler.Instr.push 2 89,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 19,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 4 }),
 YulEvmCompiler.Instr.push 2 4,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 101,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 17,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 5 }),
 YulEvmCompiler.Instr.push 2 4,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.XOR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.XOR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 158,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 126,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 22,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 3 }),
 YulEvmCompiler.Instr.push 2 4,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 138,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 13,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 4 }),
 YulEvmCompiler.Instr.push 2 4,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 150,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 2,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 5 }),
 YulEvmCompiler.Instr.push 2 4,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.XOR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.XOR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 207,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 175,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 25,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 3 }),
 YulEvmCompiler.Instr.push 2 4,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 187,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 11,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 4 }),
 YulEvmCompiler.Instr.push 2 4,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 199,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 6,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 5 }),
 YulEvmCompiler.Instr.push 2 4,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.XOR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.XOR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 228,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 2 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.NOT)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.AND)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 2 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 2 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.AND)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.XOR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 3 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 252,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 2 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 2 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.AND)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 3 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 2 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.AND)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 3 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 3 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.AND)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.XOR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.XOR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 3 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 274,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 0 }),
 YulEvmCompiler.Instr.push 1 2,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.push 1 32,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MLOAD)),
 YulEvmCompiler.Instr.push 1 224,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 294,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 0 }),
 YulEvmCompiler.Instr.push 1 5,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.push 2 800,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MLOAD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 313,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.push 1 5,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.push 2 800,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 333,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 0 }),
 YulEvmCompiler.Instr.push 1 5,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.push 2 288,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MLOAD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 352,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.push 1 5,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.push 2 288,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 441,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Env (EvmSemantics.Operation.EnvOps.CALLDATASIZE)),
 YulEvmCompiler.Instr.push 1 72,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.push 1 6,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHR)),
 YulEvmCompiler.Instr.push 1 6,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 0 }),
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 2 2848,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Env (EvmSemantics.Operation.EnvOps.CALLDATACOPY)),
 YulEvmCompiler.Instr.push 1 128,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.push 2 2848,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE8)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 0 }),
 YulEvmCompiler.Instr.push 1 3,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.push 1 8,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 3 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.SUB)),
 YulEvmCompiler.Instr.push 2 2848,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 8,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.LT)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.ISZERO)),
 YulEvmCompiler.Instr.push 2 434,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPI)),
 YulEvmCompiler.Instr.push 1 255,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 3 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 2 }),
 YulEvmCompiler.Instr.push 1 7,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.SUB)),
 YulEvmCompiler.Instr.push 1 3,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.AND)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 3 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE8)),
 YulEvmCompiler.Instr.push 1 1,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.push 2 398,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 607,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 16,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.LT)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.ISZERO)),
 YulEvmCompiler.Instr.push 2 491,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPI)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 0 }),
 YulEvmCompiler.Instr.push 1 2,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 2 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MLOAD)),
 YulEvmCompiler.Instr.push 1 224,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 3 }),
 YulEvmCompiler.Instr.push 1 5,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.push 2 800,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.push 1 1,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.push 2 448,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.push 1 16,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 64,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.LT)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.ISZERO)),
 YulEvmCompiler.Instr.push 2 603,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPI)),
 YulEvmCompiler.Instr.push 2 592,
 YulEvmCompiler.Instr.push 4 4294967295,
 YulEvmCompiler.Instr.push 2 525,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 16,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 5 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.SUB)),
 YulEvmCompiler.Instr.push 2 279,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 547,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 2 542,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 15,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 8 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.SUB)),
 YulEvmCompiler.Instr.push 2 279,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 32,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.push 2 561,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 7,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 6 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.SUB)),
 YulEvmCompiler.Instr.push 2 279,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 583,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 2 578,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 2,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 9 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.SUB)),
 YulEvmCompiler.Instr.push 2 279,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 73,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.AND)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 2 }),
 YulEvmCompiler.Instr.push 2 299,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 1,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.push 2 495,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 997,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 621,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.push 2 446,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 256,
 YulEvmCompiler.Instr.push 2 288,
 YulEvmCompiler.Instr.push 2 544,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MCOPY)),
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 64,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.LT)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.ISZERO)),
 YulEvmCompiler.Instr.push 2 935,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPI)),
 YulEvmCompiler.Instr.push 2 416,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MLOAD)),
 YulEvmCompiler.Instr.push 4 4294967295,
 YulEvmCompiler.Instr.push 2 661,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 4 }),
 YulEvmCompiler.Instr.push 2 279,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 671,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 5 }),
 YulEvmCompiler.Instr.push 2 257,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 703,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 2 686,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 6,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 697,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 5,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 7 }),
 YulEvmCompiler.Instr.push 2 212,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.push 2 714,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 5 }),
 YulEvmCompiler.Instr.push 2 163,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 725,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 7,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.AND)),
 YulEvmCompiler.Instr.push 2 288,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MLOAD)),
 YulEvmCompiler.Instr.push 4 4294967295,
 YulEvmCompiler.Instr.push 2 770,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 2 753,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 2,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 764,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 1,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 5 }),
 YulEvmCompiler.Instr.push 2 233,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 780,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 4 }),
 YulEvmCompiler.Instr.push 2 114,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.AND)),
 YulEvmCompiler.Instr.push 2 803,
 YulEvmCompiler.Instr.push 2 796,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 6,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 7,
 YulEvmCompiler.Instr.push 2 338,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 824,
 YulEvmCompiler.Instr.push 2 817,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 5,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 6,
 YulEvmCompiler.Instr.push 2 338,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 3 }),
 YulEvmCompiler.Instr.push 2 448,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 2 858,
 YulEvmCompiler.Instr.push 4 4294967295,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 4 }),
 YulEvmCompiler.Instr.push 2 849,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 3,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.AND)),
 YulEvmCompiler.Instr.push 1 4,
 YulEvmCompiler.Instr.push 2 338,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 879,
 YulEvmCompiler.Instr.push 2 872,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 2,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 3,
 YulEvmCompiler.Instr.push 2 338,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 900,
 YulEvmCompiler.Instr.push 2 893,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 1,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 2,
 YulEvmCompiler.Instr.push 2 338,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.push 2 320,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 4 4294967295,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 4 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.AND)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 0 }),
 YulEvmCompiler.Instr.push 2 288,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.push 1 1,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.push 2 633,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 8,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.LT)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.ISZERO)),
 YulEvmCompiler.Instr.push 2 993,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPI)),
 YulEvmCompiler.Instr.push 2 982,
 YulEvmCompiler.Instr.push 4 4294967295,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 2 }),
 YulEvmCompiler.Instr.push 1 5,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.push 2 544,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MLOAD)),
 YulEvmCompiler.Instr.push 2 974,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 5 }),
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.AND)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 2 }),
 YulEvmCompiler.Instr.push 2 338,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 1,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.push 2 938,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 32 30096801393348216066150629019870812290309360323781106575265595564879196741333,
 YulEvmCompiler.Instr.push 1 32,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 32 97713120620179494144499103281924613306042110463305289320944720749041786024308,
 YulEvmCompiler.Instr.push 1 64,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 32 103401920683909419998851524181533271946883635397041953977501677781292093638874,
 YulEvmCompiler.Instr.push 1 96,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 32 68861658772555408896596136419381318492474255818336515412281723562876104943975,
 YulEvmCompiler.Instr.push 1 128,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 32 17963606715593734070427349205146226040797208549161445967624525721797980728453,
 YulEvmCompiler.Instr.push 1 160,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 32 73613754823269020308648057256331568713340424865447195723827797591398097264752,
 YulEvmCompiler.Instr.push 1 192,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 32 11598916766551240033718509305487668940866266266688101202651802137680944197619,
 YulEvmCompiler.Instr.push 1 224,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 32 52721853222120111415677519898561140723485011632831808137931159571523964074226,
 YulEvmCompiler.Instr.push 2 256,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 4 1779033703,
 YulEvmCompiler.Instr.push 2 288,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 4 3144134277,
 YulEvmCompiler.Instr.push 2 320,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 4 1013904242,
 YulEvmCompiler.Instr.push 2 352,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 4 2773480762,
 YulEvmCompiler.Instr.push 2 384,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 4 1359893119,
 YulEvmCompiler.Instr.push 2 416,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 4 2600822924,
 YulEvmCompiler.Instr.push 2 448,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 4 528734635,
 YulEvmCompiler.Instr.push 2 480,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 4 1541459225,
 YulEvmCompiler.Instr.push 2 512,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 2 1367,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 2 357,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.LT)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.ISZERO)),
 YulEvmCompiler.Instr.push 2 1401,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPI)),
 YulEvmCompiler.Instr.push 2 1390,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.push 2 2848,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.push 2 612,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 64,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Dup { idx := 1 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StopArith (EvmSemantics.Operation.StopArithOps.ADD)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.Swap { idx := 0 }),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.push 2 1369,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.POP)),
 YulEvmCompiler.Instr.push 2 1413,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 7,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 2 1424,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 6,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 32,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.OR)),
 YulEvmCompiler.Instr.push 2 1439,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 5,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 64,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.push 2 1453,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 4,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 96,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.OR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.OR)),
 YulEvmCompiler.Instr.push 2 1469,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 3,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 128,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.push 2 1483,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 2,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 160,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.OR)),
 YulEvmCompiler.Instr.push 2 1498,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 1 1,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 192,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.push 2 1511,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.push 2 318,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMP)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.JUMPDEST)),
 YulEvmCompiler.Instr.push 1 224,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.SHL)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.OR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.OR)),
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.CompBit (EvmSemantics.Operation.CompareBitwiseOps.OR)),
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.StackMemFlow (EvmSemantics.Operation.StackMemFlowOps.MSTORE)),
 YulEvmCompiler.Instr.push 1 32,
 YulEvmCompiler.Instr.push 0 0,
 YulEvmCompiler.Instr.op (EvmSemantics.Operation.System (EvmSemantics.Operation.SystemOps.RETURN))]

theorem referenceInstructions_count : referenceInstructions.length = 810 := by
  decide

theorem assemble_referenceInstructions :
    assemble referenceInstructions = referenceBytecode := by
  native_decide

/-- The reference bytes packaged through the submission-generic structural
artifact interface. -/
def referenceArtifact : Challenge.EvmProof.ProgramArtifact where
  code := referenceBytecode
  instructions := referenceInstructions
  assembly_eq := assemble_referenceInstructions

/-- Byte offset of instruction `index` in the structural artifact. -/
def instructionPC (index : Nat) : Nat :=
  referenceArtifact.instructionPC index

/-- Decode a plain instruction by its index in the structural artifact. -/
theorem decodeAt_op_index (index : Nat) (o : Operation)
    (hget : referenceInstructions[index]? = some (.op o))
    (hopcode : Decode.opcodeOf (Instr.opByte o) = some o)
    (hplain : YulEvmCompiler.plainOp o) :
    Decode.decodeAt referenceBytecode (instructionPC index) = some (o, none) :=
  Challenge.EvmProof.ProgramArtifact.decodeAt_op_index
    referenceArtifact index o hget hopcode hplain

/-- Decode a PUSH instruction by its index in the structural artifact. -/
theorem decodeAt_push_index (index : Nat) (width : Fin 33) (value : UInt256)
    (hget : referenceInstructions[index]? = some (.push width value))
    (hfit : value.toNat < 256 ^ width.val) :
    Decode.decodeAt referenceBytecode (instructionPC index) =
      some (.Push ⟨width⟩, some (value, width.val)) :=
  Challenge.EvmProof.ProgramArtifact.decodeAt_push_index
    referenceArtifact index width value hget hfit

/-- A JUMPDEST at an instruction index is accepted by the pinned EVM scan. -/
theorem isValidJumpDest_index (index : Nat)
    (hget : referenceInstructions[index]? = some (.op .JUMPDEST)) :
    Decode.isValidJumpDest referenceBytecode (instructionPC index) = true :=
  Challenge.EvmProof.ProgramArtifact.isValidJumpDest_index
    referenceArtifact index hget

/-- Structural locations for the compiler-generated entry trampolines. -/
structure EntryTrampoline where
  src : Nat
  dest : Nat
  srcIndex : Nat
  destIndex : Nat
  deriving DecidableEq, Repr

def entryTrampolines : List EntryTrampoline :=
  [⟨0x001b, 0x0044, 20, 48⟩, ⟨0x0044, 0x006d, 48, 76⟩,
   ⟨0x006d, 0x009e, 76, 108⟩, ⟨0x009e, 0x00cf, 108, 140⟩,
   ⟨0x00cf, 0x00e4, 140, 159⟩, ⟨0x00e4, 0x00fc, 159, 181⟩,
   ⟨0x00fc, 0x0112, 181, 198⟩, ⟨0x0112, 0x0126, 198, 213⟩,
   ⟨0x0126, 0x0139, 213, 227⟩, ⟨0x0139, 0x014d, 227, 242⟩,
   ⟨0x014d, 0x0160, 242, 256⟩, ⟨0x0160, 0x01b9, 256, 322⟩,
   ⟨0x01b9, 0x025f, 322, 432⟩, ⟨0x025f, 0x03e5, 432, 658⟩]

/-- Every entry-trampoline table row points to the stated structural
instructions and byte offsets. This compact certificate is checked once. -/
theorem entryTrampoline_valid (t : EntryTrampoline)
    (ht : t ∈ entryTrampolines) :
    instructionPC t.srcIndex = t.src ∧
    referenceInstructions[t.srcIndex]? = some (.op .JUMPDEST) ∧
    instructionPC (t.srcIndex + 1) = t.src + 1 ∧
    referenceInstructions[t.srcIndex + 1]? =
      some (.push ⟨2, by decide⟩ (UInt256.ofNat t.dest)) ∧
    instructionPC (t.srcIndex + 2) = t.src + 4 ∧
    referenceInstructions[t.srcIndex + 2]? = some (.op .JUMP) ∧
    instructionPC t.destIndex = t.dest ∧
    referenceInstructions[t.destIndex]? = some (.op .JUMPDEST) := by
  simp only [entryTrampolines, List.mem_cons, List.not_mem_nil, or_false] at ht
  rcases ht with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl |
    rfl | rfl | rfl | rfl | rfl | rfl
  all_goals repeat' apply And.intro
  all_goals rfl

/-- Structural facts for the initial `PUSH2 0x1b; JUMP`. -/
theorem initialEntry_valid :
    instructionPC 0 = 0 ∧
    referenceInstructions[0]? =
      some (.push ⟨2, by decide⟩ (UInt256.ofNat 0x001b)) ∧
    instructionPC 1 = 3 ∧
    referenceInstructions[1]? = some (.op .JUMP) := by
  repeat' apply And.intro
  all_goals rfl

def entryTargets : List Nat :=
  0x001b :: entryTrampolines.map (fun t => t.dest)

theorem entryTarget_isValid {pc : Nat} (hpc : pc ∈ entryTargets) :
    Decode.isValidJumpDest referenceBytecode pc = true := by
  rcases List.mem_cons.mp hpc with rfl | hdest
  · have ht : (⟨0x001b, 0x0044, 20, 48⟩ : EntryTrampoline) ∈
        entryTrampolines := by simp [entryTrampolines]
    have hv := entryTrampoline_valid _ ht
    simpa [hv.1] using isValidJumpDest_index 20 hv.2.1
  · obtain ⟨t, ht, rfl⟩ := List.mem_map.mp hdest
    have hv := entryTrampoline_valid t ht
    simpa [hv.2.2.2.2.2.2.1] using
      isValidJumpDest_index t.destIndex hv.2.2.2.2.2.2.2

structure InitStore where
  index : Nat
  valueWidth : Fin 33
  value : UInt256
  offsetWidth : Fin 33
  offset : UInt256

def initStores : List InitStore :=
  [⟨659, 32, 0x428a2f9871374491b5c0fbcfe9b5dba53956c25b59f111f1923f82a4ab1c5ed5, 1, 0x20⟩,
   ⟨662, 32, 0xd807aa9812835b01243185be550c7dc372be5d7480deb1fe9bdc06a7c19bf174, 1, 0x40⟩,
   ⟨665, 32, 0xe49b69c1efbe47860fc19dc6240ca1cc2de92c6f4a7484aa5cb0a9dc76f988da, 1, 0x60⟩,
   ⟨668, 32, 0x983e5152a831c66db00327c8bf597fc7c6e00bf3d5a7914706ca635114292967, 1, 0x80⟩,
   ⟨671, 32, 0x27b70a852e1b21384d2c6dfc53380d13650a7354766a0abb81c2c92e92722c85, 1, 0xa0⟩,
   ⟨674, 32, 0xa2bfe8a1a81a664bc24b8b70c76c51a3d192e819d6990624f40e3585106aa070, 1, 0xc0⟩,
   ⟨677, 32, 0x19a4c1161e376c082748774c34b0bcb5391c0cb34ed8aa4a5b9cca4f682e6ff3, 1, 0xe0⟩,
   ⟨680, 32, 0x748f82ee78a5636f84c878148cc7020890befffaa4506cebbef9a3f7c67178f2, 2, 0x100⟩,
   ⟨683, 4, 0x6a09e667, 2, 0x120⟩,
   ⟨686, 4, 0xbb67ae85, 2, 0x140⟩,
   ⟨689, 4, 0x3c6ef372, 2, 0x160⟩,
   ⟨692, 4, 0xa54ff53a, 2, 0x180⟩,
   ⟨695, 4, 0x510e527f, 2, 0x1a0⟩,
   ⟨698, 4, 0x9b05688c, 2, 0x1c0⟩,
   ⟨701, 4, 0x1f83d9ab, 2, 0x1e0⟩,
   ⟨704, 4, 0x5be0cd19, 2, 0x200⟩]

theorem initStore_valid (w : InitStore) (hw : w ∈ initStores) :
    referenceInstructions[w.index]? = some (.push w.valueWidth w.value) ∧
    instructionPC (w.index + 1) = instructionPC w.index + w.valueWidth.val + 1 ∧
    referenceInstructions[w.index + 1]? = some (.push w.offsetWidth w.offset) ∧
    instructionPC (w.index + 2) = instructionPC (w.index + 1) + w.offsetWidth.val + 1 ∧
    referenceInstructions[w.index + 2]? = some (.op .MSTORE) ∧
    instructionPC (w.index + 3) = instructionPC (w.index + 2) + 1 := by
  simp only [initStores, List.mem_cons, List.not_mem_nil, or_false] at hw
  rcases hw with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl |
    rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  all_goals repeat' apply And.intro
  all_goals rfl

theorem mainEntry_valid :
    instructionPC 658 = 0x03e5 ∧
    referenceInstructions[658]? = some (.op .JUMPDEST) ∧
    instructionPC 659 = 0x03e6 := by
  repeat' apply And.intro
  all_goals rfl

end Challenge.Sha256.Reference.Proofs.Bytecode.Artifact
