import YulEvmCompiler.Compile

set_option warningAsError true

namespace Challenge.Bls12381G2Msm.Reference.Proofs.Compilation

/-- Generated optimized assembly entries 0 onward. -/
def frozenReferenceAssemblyChunk0 : List YulEvmCompiler.Asm :=
[YulEvmCompiler.Asm.jump 32,
 YulEvmCompiler.Asm.label 0,
 YulEvmCompiler.Asm.push 0x000000000000000000000000000000001a0111ea397fe69a4b1ba7b6434bacd7#256,
 YulEvmCompiler.Asm.push 0x64774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab#256,
 YulEvmCompiler.Asm.dup 0,
 YulEvmCompiler.Asm.dup 4,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.lt),
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.iszero),
 YulEvmCompiler.Asm.dup 2,
 YulEvmCompiler.Asm.dup 4,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.eq),
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.and),
 YulEvmCompiler.Asm.dup 2,
 YulEvmCompiler.Asm.dup 4,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.gt),
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.or),
 YulEvmCompiler.Asm.swap 4,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.swap 0,
 YulEvmCompiler.Asm.dynJump,
 YulEvmCompiler.Asm.label 32,
 YulEvmCompiler.Asm.jump 34,
 YulEvmCompiler.Asm.label 1,
 YulEvmCompiler.Asm.pushLabel 35,
 YulEvmCompiler.Asm.push 0x0000000000000000000000000000000000000000000000000000000000000000#256,
 YulEvmCompiler.Asm.dup 3,
 YulEvmCompiler.Asm.dup 3,
 YulEvmCompiler.Asm.jump 0,
 YulEvmCompiler.Asm.label 35,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.iszero),
 YulEvmCompiler.Asm.swap 2,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.swap 0,
 YulEvmCompiler.Asm.dynJump,
 YulEvmCompiler.Asm.label 34,
 YulEvmCompiler.Asm.jump 37,
 YulEvmCompiler.Asm.label 2,
 YulEvmCompiler.Asm.dup 1,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.iszero),
 YulEvmCompiler.Asm.dup 1,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.iszero),
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.and),
 YulEvmCompiler.Asm.swap 2,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.swap 0,
 YulEvmCompiler.Asm.dynJump,
 YulEvmCompiler.Asm.label 37,
 YulEvmCompiler.Asm.jump 39,
 YulEvmCompiler.Asm.label 3,
 YulEvmCompiler.Asm.dup 3,
 YulEvmCompiler.Asm.dup 2,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.eq),
 YulEvmCompiler.Asm.dup 3,
 YulEvmCompiler.Asm.dup 2,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.eq),
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.and),
 YulEvmCompiler.Asm.swap 4,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.swap 0,
 YulEvmCompiler.Asm.dynJump,
 YulEvmCompiler.Asm.label 39,
 YulEvmCompiler.Asm.jump 41,
 YulEvmCompiler.Asm.label 4,
 YulEvmCompiler.Asm.dup 3,
 YulEvmCompiler.Asm.dup 2,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.add),
 YulEvmCompiler.Asm.swap 5,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.dup 1,
 YulEvmCompiler.Asm.dup 6,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.lt),
 YulEvmCompiler.Asm.dup 3,
 YulEvmCompiler.Asm.dup 2,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.add),
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.add),
 YulEvmCompiler.Asm.swap 4,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pushLabel 43,
 YulEvmCompiler.Asm.push 0x0000000000000000000000000000000000000000000000000000000000000000#256,
 YulEvmCompiler.Asm.dup 7,
 YulEvmCompiler.Asm.dup 7,
 YulEvmCompiler.Asm.jump 0,
 YulEvmCompiler.Asm.label 43,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.iszero),
 YulEvmCompiler.Asm.jumpi 42,
 YulEvmCompiler.Asm.push 0x000000000000000000000000000000001a0111ea397fe69a4b1ba7b6434bacd7#256,
 YulEvmCompiler.Asm.push 0x64774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab#256,
 YulEvmCompiler.Asm.dup 0,
 YulEvmCompiler.Asm.dup 8,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.sub),
 YulEvmCompiler.Asm.dup 8,
 YulEvmCompiler.Asm.dup 2,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.gt),
 YulEvmCompiler.Asm.dup 3,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.add),
 YulEvmCompiler.Asm.dup 8,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.sub),
 YulEvmCompiler.Asm.swap 7,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.dup 0,
 YulEvmCompiler.Asm.swap 8,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.label 42,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.swap 0,
 YulEvmCompiler.Asm.swap 1,
 YulEvmCompiler.Asm.dynJump,
 YulEvmCompiler.Asm.label 41,
 YulEvmCompiler.Asm.jump 45,
 YulEvmCompiler.Asm.label 5,
 YulEvmCompiler.Asm.dup 3,
 YulEvmCompiler.Asm.dup 2,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.sub),
 YulEvmCompiler.Asm.swap 5,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.dup 1,
 YulEvmCompiler.Asm.dup 4,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.gt),
 YulEvmCompiler.Asm.dup 3,
 YulEvmCompiler.Asm.dup 2,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.sub),
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.sub),
 YulEvmCompiler.Asm.swap 4,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.push 0x000000000000000000000000000000001a0111ea397fe69a4b1ba7b6434bacd7#256,
 YulEvmCompiler.Asm.dup 0,
 YulEvmCompiler.Asm.dup 6,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.gt),
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.iszero),
 YulEvmCompiler.Asm.jumpi 46,
 YulEvmCompiler.Asm.push 0x64774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab#256,
 YulEvmCompiler.Asm.dup 0,
 YulEvmCompiler.Asm.dup 8,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.add),
 YulEvmCompiler.Asm.dup 8,
 YulEvmCompiler.Asm.dup 1,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.lt),
 YulEvmCompiler.Asm.dup 3,
 YulEvmCompiler.Asm.dup 9,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.add),
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.add),
 YulEvmCompiler.Asm.swap 7,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.dup 0,
 YulEvmCompiler.Asm.swap 8,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.label 46,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.swap 0,
 YulEvmCompiler.Asm.swap 1,
 YulEvmCompiler.Asm.dynJump,
 YulEvmCompiler.Asm.label 45,
 YulEvmCompiler.Asm.jump 48,
 YulEvmCompiler.Asm.label 6,
 YulEvmCompiler.Asm.dup 3,
 YulEvmCompiler.Asm.dup 2,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.mul),
 YulEvmCompiler.Asm.swap 6,
 YulEvmCompiler.Asm.pop,
 YulEvmCompiler.Asm.push 0x0000000000000000000000000000000000000000000000000000000000000000#256,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.not),
 YulEvmCompiler.Asm.dup 4,
 YulEvmCompiler.Asm.dup 3,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.mulmod),
 YulEvmCompiler.Asm.dup 7,
 YulEvmCompiler.Asm.dup 1,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.lt),
 YulEvmCompiler.Asm.dup 8,
 YulEvmCompiler.Asm.dup 2,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.sub),
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.sub),
 YulEvmCompiler.Asm.dup 5,
 YulEvmCompiler.Asm.dup 3,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.mul),
 YulEvmCompiler.Asm.push 0x0000000000000000000000000000000000000000000000000000000000000000#256,
 YulEvmCompiler.Asm.op (YulSemantics.EVM.Op.not)]

end Challenge.Bls12381G2Msm.Reference.Proofs.Compilation
