#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C

cd "$(git rev-parse --show-toplevel)/foundry"

test_output=""
if ! test_output="$(
  forge test --match-contract Bls12381G1AddGasTest --match-test test_report -vv 2>&1
)"; then
  printf '%s\n' "$test_output" >&2
  exit 1
fi
readonly test_output

declare -A reference_gas=()
declare -A native_gas=()
declare -A input_size=()
row_count=0
while IFS=, read -r marker label bytes reference native; do
  [[ "$marker" == "BLS_GAS" ]] || continue
  [[ "$bytes" =~ ^[0-9]+$ && "$reference" =~ ^[0-9]+$ && "$native" =~ ^[0-9]+$ ]] || {
    printf 'error: malformed BLS gas row: %s,%s,%s,%s,%s\n' \
      "$marker" "$label" "$bytes" "$reference" "$native" >&2
    exit 1
  }
  input_size["$label"]="$bytes"
  reference_gas["$label"]="$reference"
  native_gas["$label"]="$native"
  row_count=$((row_count + 1))
done < <(printf '%s\n' "$test_output" | sed -n 's/^[[:space:]]*\(BLS_GAS,\)/\1/p')

total_line="$(
  printf '%s\n' "$test_output" | sed -n 's/^[[:space:]]*BLS_GAS_TOTAL,//p'
)"
IFS=, read -r total_vectors bytecode_size reference_total native_total <<< "$total_line"

readonly labels=(
  "infinity + infinity"
  "generator + infinity"
  "infinity + generator"
  "generator + negative"
  "generator doubling"
  "generator + double"
)

if [[ "$row_count" -ne 6 || "$total_vectors" != "6" || \
      ! "$bytecode_size" =~ ^[0-9]+$ || ! "$reference_total" =~ ^[0-9]+$ || \
      ! "$native_total" =~ ^[0-9]+$ ]]; then
  printf 'error: incomplete BLS gas report output\n%s\n' "$test_output" >&2
  exit 1
fi

for label in "${labels[@]}"; do
  if [[ "${input_size[$label]:-}" != "256" || "${native_gas[$label]:-}" != "375" || \
        ! "${reference_gas[$label]:-}" =~ ^[0-9]+$ ]]; then
    printf 'error: missing or invalid BLS gas vector %s\n' "$label" >&2
    exit 1
  fi
done

ratio="$(
  awk -v numerator="$reference_total" -v denominator="$native_total" \
    'BEGIN { printf "%.2f×", numerator / denominator }'
)"

printf '%s\n' '<!-- BEGIN GENERATED BLS12381G1ADD GAS REPORT -->'
printf '%s\n\n' '## Gas leaderboard'
printf '%s\n\n' \
  'Generated by `scripts/report-bls12381-g1add-gas.sh`; CI checks that this section is current.'
printf '%s\n' \
  'Gas is measured by concrete execution of the generated artifact under the' \
  'pinned Foundry/revm Osaka EVM. `GasProbe` reports callee-frame gas, excluding' \
  'transaction and call-entry overhead. Every measured vector returns the native' \
  '`0x0b` result. These measurements test the compiler artifact; they are not Lean' \
  'proofs and do not extend the source-correctness theorem to EVM bytecode.'
printf '\n'
printf '%s\n' \
  'The six 256-byte vectors cover both infinity identities, opposite points,' \
  'doubling, and unequal finite-point addition. Native G1ADD costs 375 gas per' \
  'successful vector (2,250 total). Each measurement forwards at most 1,000,000' \
  'gas, so a broken artifact fails promptly. Malformed inputs remain tested for' \
  'correctness but are not ranked: their required `INVALID` halt consumes all' \
  'gas forwarded by the caller, so it has no context-independent numeric frame cost.'
printf '\n'
printf '%s\n' '| implementation | bytes | ∞ + ∞ | G + ∞ | ∞ + G | G + (−G) | G + G | G + 2G | all valid | vs native | status |'
printf '%s\n' '|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|'
printf '| [Reference Yul](Reference/reference.yul) | %s' "$bytecode_size"
for label in "${labels[@]}"; do
  printf ' | %s' "${reference_gas[$label]}"
done
printf ' | %s | %s | measured artifact |\n' "$reference_total" "$ratio"

printf '\n%s\n\n' '### Proved gas bounds'
printf '%s\n' \
  'None claimed. Gas is absent from the source semantics used by the G1ADD proof,' \
  'and proving a compiled-bytecode gas schedule would cross this challenge’s' \
  'deliberate source-only correctness boundary.'
printf '\n%s\n' '<!-- END GENERATED BLS12381G1ADD GAS REPORT -->'
