import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalYMul
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalYMulStmt
#print axioms step_pointAddUnequalYMulStmt
