import Challenge.Bls12381G1Msm.Reference.Proofs.SourceFpMulMemory

set_option warningAsError true

open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics

#check fpMulFinalState_readBytes_after_scratch
#check fpMulFinalState_loadWord_after_scratch
