import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalLambda
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalLambdaStmt
#print axioms step_pointAddUnequalLambdaStmt
