import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalX3
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalX3Stmt
#print axioms step_pointAddUnequalX3Stmt
