import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalReadbackXValue

set_option warningAsError true

open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics

#check pointAddUnequalConcretePostState_readbackXValue
#check pointAddUnequalOutputX_eq_result
