import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalXSubLeftFull
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalXSubLeftStmt
#print axioms step_pointAddUnequalXSubLeftStmt
