import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalInvSequence
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalInvBody
#print axioms step_pointAddUnequalInvBody
