import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalInvCall
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check exec_pointAddUnequalInvCall
#print axioms exec_pointAddUnequalInvCall
