import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalNumeratorRaw

set_option warningAsError true

open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics

#check step_pointAddUnequalNumeratorRawDecl
#check step_pointAddUnequalNumeratorRawBlock
