import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalXSubBridge
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalXSubStmt
#print axioms step_pointAddUnequalXSubStmt
