import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalDenominator

set_option warningAsError true

open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics

#check pointAddUnequalDenominatorRawBody_eq
#check pointAddUnequalDenominatorRaw
