import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalDeltaEnvLookup
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalDeltaInitAndStmt
#check pointAddUnequalDeltaConcreteEnv_lambdaHi
#check pointAddUnequalDeltaConcreteEnv_lambdaLo
#print axioms step_pointAddUnequalDeltaInitAndStmt
