import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalNumeratorRepair

set_option warningAsError true

open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics

#check step_pointAddUnequalNumeratorRepair
