import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalXSubLeftEnvLookup
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check pointAddUnequalXSubLeftEnv_hi
#check pointAddUnequalXSubLeftEnv_lo
#print axioms pointAddUnequalXSubLeftEnv_hi
