import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalInvBase
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalInvBaseGeneric
#print axioms step_pointAddUnequalInvBaseGeneric
