import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalPostludeBridge

set_option warningAsError true

open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics

#check pointAddUnequalPostContext_xHi
#check pointAddUnequalPostContext_xLo
