import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalXSubLeftOutputs
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalXSubLeftOutputs
#print axioms step_pointAddUnequalXSubLeftOutputs
