import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalNumeratorFull

set_option warningAsError true

open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics

#check step_pointAddUnequalNumerator
