import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalXOperands

set_option warningAsError true

open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics

#check pointAddUnequalXSubLeftLimbs_eq
#check pointAddUnequalXSubRightLimbs_eq
