import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalDenominatorWords
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalDenominatorLowGeneric
#check step_pointAddUnequalDenominatorHighGeneric
