import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalInvPrefix
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalInvPrefix
#print axioms step_pointAddUnequalInvPrefix
