import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalNumeratorLeftLo

set_option warningAsError true

open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics

#check step_pointAddUnequalNumeratorLeftLo
