import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalMath

set_option warningAsError true

open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics

#check canonical_pointAddUnequalLambda
#check pointAddUnequalLambda_toLawful
