import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalXSubRightRaw
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalXSubRightRawGeneric
#print axioms step_pointAddUnequalXSubRightRawGeneric
