import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalDenominatorRightHi
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalDenominatorRightHi
