import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalDenominatorRaw
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalDenominatorRawDecl
#check step_pointAddUnequalDenominatorRawBlock
